spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        followerEventChannel:
          name: follower_channel
        goalCompletedEvent:
          name: goal_completed_event_channel
        profilePicEventChannel:
          name: profile_pic_channel
        mentorshipRequest:
          name: mentorship_request_topic
        recommendationRequestEvent:
          name: recommendation_request_event
        profileViewChannel:
          name: profile_view_channel
        skillAcquiredChannel:
          name: skill_acquired_channel
        projectChannel:
          name: project_channel
        mentorshipStartEvent:
          name: mentorship_start_event_channel
        goalSetChannel:
          name: goal_set_channel

servlet:
  multipart:
    max-file-size: 5242880

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  retry:
    max-attempts: 5
    backoff-delay: 5000

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    connectionTimeout: 10_000
    socketTimeout: 10_000
    bucketDefaultAvatarsName: usersdefaultavatars #should be lowerCase
    defaultProfilePicture: defaultAvatar.png
    remoteFilename: pic.png
  imagegenerator:
    endpoint: https://api.dicebear.com/9.x
    paths:
      get: adventurer-neutral/png
  postService:
    endpoint: http://localhost:8081
    requiredHeaders: x-user-id

premium:
  schedule: "0 0 0 * * *"
  batch-size: 100

thread-pool-config:
  size: 5