name: ci_user_service

on:
  pull_request:
    branches: [ "feature-BJS2-40724-pipeline" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
              name: Package
              path: build/libs