name: User-Service CI

on:
  push:
    branches:
      - Dragon-master-stream7
  pull_request:
    branches:
      - Dragon-master-stream7

jobs:
  test-build:
    name: Test and Build User-Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: ./gradlew test

      - name: Build the application
        run: ./gradlew build
