name: CI Pipeline

on:
  pull_request:
    branches:
      - feature-BJS2-40776

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get changed Java files
        id: changed-files
        run: |
          # Получаем список измененных Java файлов в pull request
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Checkstyle on changed files
        run: |
          # Если есть измененные файлы, запускаем checkstyle только для них
            if [ -n "$CHANGED_FILES" ]; then
              ./gradlew checkstyleMain --include "$CHANGED_FILES" checkstyleTest --include "$CHANGED_FILES"
            else
              echo "No Java files changed, skipping Checkstyle."
            fi

      - name: Build and run tests
        run: ./gradlew test

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/