name: Java CI with Gradle For Medusa Stream 7

on: [ pull_request ]

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Build and Run Tests With Gradle
        run: ./gradlew test --no-daemon