name: CI Pipeline

on:
  pull_request:
    branches:
      - feature-BJS2-40776

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug changed files
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Current commit: ${{ github.sha }}"
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }}
          echo "Changed files:"
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }} | grep '\.java$' || echo "No Java files found."

      - name: Get changed Java files in main and test
        id: changed-files
        run: |
          git fetch origin
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} | grep -E 'src/(main|test)/.*\.java$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Checkstyle on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running Checkstyle on:"
            echo "$CHANGED_FILES"
            for FILE in $CHANGED_FILES; do
              ./gradlew checkstyleMain checkstyleTest --include-build "$FILE" || exit 1
            done
          else
            echo "No Java files changed in main or test, skipping Checkstyle."
          fi

      - name: Build and run tests
        run: ./gradlew test

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
